name: Deploy React App to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install
        working-directory: ./SpeechHelp

      - name: Build Project
        run: npm run build
        working-directory: ./SpeechHelp
